//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("Ninject.Extensions.Wcf: WCF Extension for Ninject")]
[assembly: AssemblyCompanyAttribute("Innovatian Software, LLC")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2009-2010 Innovatian Software, LLC and contributors")]
[assembly: AssemblyVersionAttribute("2.1.0.17")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]

